// <auto-generated />
using System;
using ElectronicSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.CalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalcType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("calculation_history", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = 0L,
                            Description = "Componentes limitadores de corriente",
                            DisplayOrder = 0,
                            Icon = "resistor",
                            Name = "Resistencias",
                            Slug = "resistencias",
                            UpdatedAt = 0L
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = 0L,
                            Description = "Almacenamiento de energía",
                            DisplayOrder = 0,
                            Icon = "capacitor",
                            Name = "Capacitores",
                            Slug = "capacitores",
                            UpdatedAt = 0L
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = 0L,
                            Description = "Diodos, Transistores e ICs",
                            DisplayOrder = 0,
                            Icon = "ic",
                            Name = "Semiconductores",
                            Slug = "semiconductores",
                            UpdatedAt = 0L
                        });
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.CircuitComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("ComponentId");

                    b.ToTable("circuit_components", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentPinout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinFunction")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PinNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "PinNumber")
                        .IsUnique();

                    b.ToTable("component_pinouts", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("component_specs", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Tag")
                        .IsUnique();

                    b.ToTable("component_tags", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.GuideComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuideId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("GuideId");

                    b.ToTable("guide_components", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ImplementationGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CircuitDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tips")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MainComponentId");

                    b.ToTable("implementation_guides", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ResistorColorBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DigitValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<int?>("TempCoeffPpm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TolerancePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ColorName")
                        .IsUnique();

                    b.ToTable("resistor_color_bands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorName = "black",
                            DigitValue = 0,
                            HexCode = "#000000",
                            Multiplier = 1.0
                        },
                        new
                        {
                            Id = 2,
                            ColorName = "brown",
                            DigitValue = 1,
                            HexCode = "#8B4513",
                            Multiplier = 10.0,
                            TempCoeffPpm = 100,
                            TolerancePct = 1.0
                        },
                        new
                        {
                            Id = 3,
                            ColorName = "red",
                            DigitValue = 2,
                            HexCode = "#FF0000",
                            Multiplier = 100.0,
                            TempCoeffPpm = 50,
                            TolerancePct = 2.0
                        },
                        new
                        {
                            Id = 4,
                            ColorName = "orange",
                            DigitValue = 3,
                            HexCode = "#FFA500",
                            Multiplier = 1000.0,
                            TempCoeffPpm = 15
                        },
                        new
                        {
                            Id = 5,
                            ColorName = "yellow",
                            DigitValue = 4,
                            HexCode = "#FFFF00",
                            Multiplier = 10000.0,
                            TempCoeffPpm = 25
                        },
                        new
                        {
                            Id = 6,
                            ColorName = "green",
                            DigitValue = 5,
                            HexCode = "#008000",
                            Multiplier = 100000.0,
                            TolerancePct = 0.5
                        },
                        new
                        {
                            Id = 7,
                            ColorName = "blue",
                            DigitValue = 6,
                            HexCode = "#0000FF",
                            Multiplier = 1000000.0,
                            TolerancePct = 0.25
                        },
                        new
                        {
                            Id = 8,
                            ColorName = "violet",
                            DigitValue = 7,
                            HexCode = "#EE82EE",
                            Multiplier = 10000000.0,
                            TolerancePct = 0.10000000000000001
                        },
                        new
                        {
                            Id = 9,
                            ColorName = "grey",
                            DigitValue = 8,
                            HexCode = "#808080",
                            Multiplier = 100000000.0,
                            TolerancePct = 0.050000000000000003
                        },
                        new
                        {
                            Id = 10,
                            ColorName = "white",
                            DigitValue = 9,
                            HexCode = "#FFFFFF",
                            Multiplier = 1000000000.0
                        },
                        new
                        {
                            Id = 11,
                            ColorName = "gold",
                            HexCode = "#FFD700",
                            Multiplier = 0.10000000000000001,
                            TolerancePct = 5.0
                        },
                        new
                        {
                            Id = 12,
                            ColorName = "silver",
                            HexCode = "#C0C0C0",
                            Multiplier = 0.01,
                            TolerancePct = 10.0
                        });
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.SavedCircuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CircuitDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("saved_circuits", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("user_favorites", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("user_notes", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Categoria", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.CircuitComponent", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.SavedCircuit", "Circuit")
                        .WithMany("Components")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentPinout", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany("Pinouts")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentSpec", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany("Specs")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ComponentTag", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany("Tags")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Componente", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Categoria", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.GuideComponent", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicSystem.Domain.Entities.ImplementationGuide", "Guide")
                        .WithMany("Bom")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ImplementationGuide", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "MainComponent")
                        .WithMany()
                        .HasForeignKey("MainComponentId");

                    b.Navigation("MainComponent");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.UserFavorite", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.UserNote", b =>
                {
                    b.HasOne("ElectronicSystem.Domain.Entities.Componente", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ElectronicSystem.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ElectronicSystem.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicSystem.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ElectronicSystem.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Components");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.Componente", b =>
                {
                    b.Navigation("Pinouts");

                    b.Navigation("Specs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.ImplementationGuide", b =>
                {
                    b.Navigation("Bom");
                });

            modelBuilder.Entity("ElectronicSystem.Domain.Entities.SavedCircuit", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
